# 공통사항들 모아놓음

spring:
  # TODO : 기본적으로 Http exeption의 메세지를 표시하지 않도록 되어있음. (보안 문제) 메세지는 표시되도록 풀어주기
  server:
    error:
      include-message: true

  profiles:
    active: local

  datasource:
    # DB 사용자 아이디와 password 작성
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache: # redis 설정
    type: redis
    port: 6379

  redis:
    host: 34.83.181.251

  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update # application 실행 시점에 기존 ddl 정보를 다 지우고 다시 실행시킨다. 그대로 유지하려면 none
    properties:
      hibernate:
        # show_sql: true # jpa, hibernate가 생성하는 모든 sql이 sout으로 찍힌다
        # 운영환경에서는 sout이 아닌 log로 나타내야 한다
        format_sql: true
---

# 배포용 profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: > # localhost나 127.0.0.1이 아닌 도커 컨테이너 이름으로 설정해야 한다고 함...
      jdbc:mysql://mysql:3306/stocking?
      useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&
      allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnection=true

---
# TODO : docker-compose를 이용해서 컨테이너 설정하고, datasource 설정 다시하기
# 개발환경용
# 146.56.100.95 - oracle
# 52.78.111.36 - 우성이 aws
spring:
  config:
    activate:
      on-profile: local
  datasource: #database source 작성
    url: > # localhost 부분 클라우드 ip로 변경. 하지만 배포할 때에는 localhost로 되어 있어야 접근할 수 있음.
      jdbc:mysql://146.56.100.95:3306/stocking?
      useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&
      allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnection=true

---
