spring:
  datasource:
    url: >
      jdbc:mysql://localhost:3306/stocking?
      useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&
      allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true